### ISSUE TITLE
MoveTargetOutOfBoundsException

### ISSUE THREAD

**Issue by umarambh** [mozilla/GitHub_Selenium#6]
MoveTargetOutOfBoundsException is occurring in more recent times when used in Drag and drop scenario. This exception started to observed first with vertical movement and slowly with horizontal drag and drop actions too. Wanted someone to look into.
Error description:- MoveTargetOutOfBoundsException: Message: (1428, 545) is out of bounds of viewport width (1152) and height (847).
Also checked to make sure browser window is maximized, Firefox version 69.0, OS tested on : Mac OS 10.14.5 and Linux.
This was absolutely working fine without issue. No upgrades have been done to the environment.

To Reproduce
=========

Open firefox latest version on Linux or Mac OSX( tested on 10.14.x) version
Open AUT, browser maximized
Using RFSelenium library trying to move an element horizontally or vertically with keyword Dragdrop by offset $locator xoffset yoffset
Get MoveTargetOutOfBoundsException with outbounds viewport width xxx and height xxx
Behaviour is see: Error i see:MoveTargetOutOfBoundsException: Message: (1428, 545) is out of bounds of viewport width (1152) and height (847)

Environment
Mac OSX 10.14.x, Linux CentOS 7.6.1810 AWS EC2
Env: Robot Framework 3.1.2 ,Python 3.7.1 on linux,Selenium 3.14.0,

**Comment by hwine** [comment]
@umarambh -- this project is only intended to support use on github.com to access web pages protected by a login requiring 2FA. It is not intended for general site or browser testing.

I recommend you use Selenium directly.
